name: jetleaf_utils
description: A library that provides high-level of utilities for the Jetleaf application.
version: 1.0.0

publish_to: https://onepub.dev/api/fahnhnofly/

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_utils

topics:
  - Utils
  - Helper

keywords:
  - Utils
  - Helper

environment:
  sdk: ^3.9.0

dependencies:
  jetleaf_lang:
    hosted: https://onepub.dev/api/fahnhnofly/
    version: ^1.0.0
  jetleaf_logging:
    hosted: https://onepub.dev/api/fahnhnofly/
    version: ^1.0.0

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0